#! /usr/bin/env bash
VERSION="1.0"
if [[ "$1" == "-v" || "$1" == "--version" ]]; then
    echo "systemd-coffeed $VERSION"
    exit 0
fi







	echo '    (  )   (   )  )'
	echo '     ) (   )  (  ('
	echo '     ( )  (    ) )'
	echo '     _____________'
	echo '    <_____________> ___'
	echo '    |             |/ _ \'
	echo '    |               | | |'
	echo '    |               |_| |'
	echo '    |             |\___/'
	echo '     \___________/     '

